server:
  port: 8082
spring:
  application:
    name: cards
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/ms-cards-db
    username: postgres
    password: password
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: optional:configserver:http://localhost:8070/
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: '*'
