server:
  port: 8082
spring:
  application:
    name: cards
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/ms-cards-db
    username: postgres
    password: password
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: optional:configserver:http://localhost:8070/
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# Info for eureka-server microservice registration
info:
  app:
    name: "cards"
    description: "MS Bank Cards rest service"
    version: "1.0.0"
